import os

print("-----Scaling train.svm to [0,1]-----")
os.system('svm-scale -l 0 -c 1 my_train.svm > my_trainscale.svm')
print("Result store in my_trainscale.svm")
print("")
print("-----Scaling test.svm to [0,1]------")
os.system('svm-scale -l 0 -c 1 my_test.svm > my_testscale.svm')
print("Result store in my_testscale.svm")
print("")
print("-----Training SVM Model-------------")
os.system('svm-train -s 1 my_trainscale.svm my_trainscale.model')
print("-----Result store in my_trainscale.model")
print("")
print("-----Predicting and Accuracy--------")
os.system('svm-predict my_testscale.svm my_trainscale.model my_testscale.result')
print("Result store in my_testscale.result")
